### ISSUE TITLE
neo4j 4.x and Ruby 3.x

### ISSUE THREAD

**Issue by dstaehler** [neo4jrb/neo4j-ruby-driver#127]
Hello all,

I'm trying to use the activegraph and neo4j-ruby-driver on neo4j 4.x and Ruby 3.x (MRI) with MAC OS Catalina. I tried a few combinations starting with neo4j 4.0 up to the current version as well as Ruby 3.0 up to 3.1.1

The goal is to execute pure Cypher queries right from Ruby code. No fancy things just run Cypher.

I always run into problems that the Seabolt connector returns:

Neo4j::Driver::Exceptions::SessionExpiredException: code: `d`, error: `13`, state: `4`, error_context: `_open(/tmp/seabolt-20220320-8284-1q4zdm2/seabolt-1.7.4/src/seabolt/src/bolt/communication.c:74): unable to establish connection`

Beside from some deprecation warnings (which I ignore for the time being), is there a known neo4j / Ruby combination on (an almost current version combination) that is know to work well or do I miss something different.

Any hint is greatly appreciated

Doug

**Comment by klobuczek** [comment]
While I don't see any problem with ruby 3.x there is a restriction on supported neo4j versions: https://neo4j.com/developer/kb/neo4j-supported-versions/

**Comment by klobuczek** [comment]
However, only two activegraph specs are failing here https://github.com/neo4jrb/activegraph/actions/runs/1885392127
So you could reverse engineer why it is working there but not for you. In any case, this configuration is unsupported and we will not work any further on that driver version. neo4j-ruby-driver 4.4.0.beta will be available probably within a month.

**Comment by dstaehler** [comment]
Thanks for the clarification. I'll check if I can find the specific issue within my config
