### ISSUE TITLE
Automatic installation of seabolt on different platforms

### ISSUE THREAD

**Issue by klobuczek** [neo4jrb/neo4j-ruby-driver#13]
The seabolt c library does not have an os package installer yet. We have to find a way to automatically install the lib for the most common platforms on `gem install`. Requiring users to install seabolt manually would make the gem for most users unacceptable.

**Comment by lkalwa** [comment]
@klobuczek I would like to pick up this

**Comment by klobuczek** [comment]
Closing due to high complexity and limited time.

**Comment by thanhtoan1196** [comment]
any updates?

**Comment by fbiville** [comment]
@thanhtoan1196 Seabolt is not maintained anymore so this is not likely to happen.
