### ISSUE TITLE
not accessible for 4.X driver from rubygems.org

### ISSUE THREAD

**Issue by RundongGao** [neo4jrb/neo4j-ruby-driver#155]
The latest version of neo4j-ruby-driver on https://rubygems.org/gems/neo4j-ruby-driver is 1.7.6.
Flowing the instruction on https://github.com/neo4jrb/neo4j-ruby-driver#installation wouldn't be able to install any of the 4.X version.

Also tried to add 
```
gem 'neo4j-ruby-driver', git: 'https://github.com/neo4jrb/neo4j-ruby-driver.git', branch: '4.4'
```
to gemfile and failed because of the source code is missing a gemspec file.

Could you provide instructions of how to use the 4.4 or any of the 4.X version of the driver?

**Comment by klobuczek** [comment]
the 1.7 driver supports neo4j up to version 4.0 (see https://github.com/neo4jrb/neo4j-ruby-driver#server-compatibility)
There is neo4j-java-driver 4.4 which is pretty much a driver with identical api but just for jruby.
the current neo4j-ruby-driver uses hoe which generates the gemspec. The README has the steps. But you won't be able to use it from source unless you create your own fork and commit the gemspec. 
Within a week we'll release 4.4 alpha version of the pure ruby driver

**Comment by RundongGao** [comment]
hey @klobuczek Thanks for explaining!
any update on the 4.4 alpha version of the pure ruby driver?

**Comment by klobuczek** [comment]
@RundongGao https://rubygems.org/gems/neo4j-ruby-driver/versions/4.4.0.alpha.6

**Comment by RundongGao** [comment]
Awesome! thank you so much @klobuczek ! closing the issue
