### ISSUE TITLE
No pure Ruby build for 4.4.x?

### ISSUE THREAD

**Issue by delner** [neo4jrb/neo4j-ruby-driver#177]
There's an 4.4.0.alpha for Ruby MRI 3.x, but no gem build on `https://rubygems.org` for `4.4.1`.

Setting `spec.add_dependency 'neo4j-ruby-driver', '~> 4.4'` in my `.gemspec` fails with:

```
Could not find gem 'neo4j-ruby-driver (~> 4.4) x86_64-linux', which is required by gem 'foo', in rubygems repository
https://rubygems.org/ or installed locally.

The source contains the following gems matching 'neo4j-ruby-driver (~> 4.4)':
  * neo4j-ruby-driver-4.4.0-java
  * neo4j-ruby-driver-4.4.1-java
```

Setting `spec.add_dependency 'neo4j-ruby-driver', '~> 4.4.0.alpha.6'` installs OK though.

**Comment by klobuczek** [comment]
There is no 4.4.0 or 4.4.1 released for MRI. The latest MRI version is 4.4.0.alpha.6. The other versions are for jruby only.
