### ISSUE TITLE
Async gem v2.14.2 breaks neo4j-ruby-driver

### ISSUE THREAD

**Issue by cguess** [neo4jrb/neo4j-ruby-driver#232]
The [async gem](https://github.com/socketry/async) was recently updated [here](https://github.com/socketry/async/blob/0bcaebad2d15c6870670d38598af39c56fb00e82/lib/async/queue.rb#L85) causing any requests from this gem to fail with an arguments error

```
PageTest#test_page_node_requires_url_and_host_name:
ArgumentError: wrong number of arguments (given 0, expected 1)
    /Users/christopher/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/async-2.14.1/lib/async/queue.rb:85:in `signal'
    /Users/christopher/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/neo4j-ruby-driver-4.4.5/ruby/neo4j/driver/internal/handlers/pulln/auto_pull_response_handler.rb:6:in `signal'
```
Requiring the previous version such as
```
# Scraping management
gem "async", "2.12.0"
gem "activegraph" # For example, see https://rubygems.org/gems/activegraph/versions for the latest versions
gem "neo4j-ruby-driver"
```
Fixes this problem, and should either be required in the gemspec file or this should be updated to handle it.

**Comment by JonhyOliveira** [comment]
bump - experienced the same issue today

**Comment by klobuczek** [comment]
neo4j-ruby-driver (4.4.6) released. Provided upper bound for async.
