### ISSUE TITLE
neo4j+s protocol is not supported

### ISSUE THREAD

**Issue by jdtriska** [neo4jrb/neo4j-ruby-driver#52]
Hi there,

I've been trying to get neo4j-ruby-driver working with Neo4j Aura. However, Aura requires the use of the `neo4j+s` protocol, which appears to be unsupported by the native ruby version of this gem. I have tried substituting bolt, as well as turning on encryption, but doing so returns the following:
```
code: `f`, error: `15`, state: `4`, error_context: `plain_socket_recv(/tmp/seabolt/src/seabolt/src/bolt/communication-plain.c:254), recv returned 0`
```
Using the `neo4j+s` protocol returns the following:
```
Unsupported URI scheme: neo4j+s
```
If you have any suggestions or comments on how this may (or may not) work, please let me know.

Thank you,

Joey

**Comment by fbiville** [comment]
This new connection scheme is only supported by Neo4j 4 compatible drivers.
The only possible option at the moment is to use the JRuby variant as far as I know.

**Comment by jdtriska** [comment]
Ah, I see, thank you. It looks like Aura also supports the `bolt+routing` protocol--do you know if that's supported? It seems to be mentioned in the [examples](https://github.com/neo4jrb/neo4j-ruby-driver/blob/19b11107aa2f80739622426b4023534c56600471/docs/dev_manual_examples.rb#L29-L49), as well as in the code of [driver_factory.rb](https://github.com/neo4jrb/neo4j-ruby-driver/blob/a3c20f3bdf4486d835d44281f17ce922609640b3/ffi/neo4j/driver/internal/driver_factory.rb). However, at the moment, the driver returns `Could not perform discovery. No routing servers available.`

Again, thanks for your help.

**Comment by klobuczek** [comment]
@jdtriska I am not very familiar with Aura, but it seem unreasonable that Aura would support bolt+routing but not neo4j protocol. The neo4j protocol is the safest to use as it should work in cluster or on single instance. The +s encyption suffixes are not supported in drivers 1.7. You can configure encryption via driver configuration.

**Comment by jdtriska** [comment]
@klobuczek @fbiville, thanks for your help with this. It turns out that bolt+routing actually does work (you can just substitute bolt+routing for neo4j+s in the database URL you get from the Aura dashboard). My problem turned out to be that I wasn't setting the password to the correct value. After making sure that I had the correct credentials, I was able to write data from the ruby (non-jruby) driver to Aura. In case anyone else does this and gets confused by the error returned when credentials are incorrect, here's a sample of the code I'm using to connect:

```
driver = ::Neo4j::Driver::GraphDatabase.driver(db_url, ::Neo4j::Driver::AuthTokens.basic(username, password),
          encryption: true,
          max_connection_lifetime: 30.minutes,
          max_connection_pool_size: 50,
          connection_acquisition_timeout: 2.minutes)
```

In the above, `db_url` would be your Aura URL, e.g. `bolt+routing://12345678.databases.neo4j.io", and `username` and `password` would be the username and password provided by Aura.
