### ISSUE TITLE
Please release the multi-byte fix as a new gem version

### ISSUE THREAD

**Issue by yourpalal** [neo4jrb/neo4j-ruby-driver#62]
I would really appreciate it if you could release the fix for multi-byte unicode characters in 8ba044707b76db112f41a2e621dfbfcf442b879. I'm currently working on a major upgrade from neo4jrb to activegraph, and this is a blocking issue for the project.

I spent probably four hours tracking a bug down yesterday, realised that adding multi-byte characters caused a truncated query string, and then came here to make a PR only to realise that it had been fixed two weeks ago!

**Comment by klobuczek** [comment]
neo4j-ruby-driver 1.7.5 released

**Comment by yourpalal** [comment]
Thank you @klobuczek!
